# https://aka.ms/yaml

jobs:
  - job:
    displayName: linux
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - script: |
          mkdir -p ~/miniforge3
          curl -L https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -o ~/miniforge3/miniforge.sh
          bash ~/miniforge3/miniforge.sh -b -u -p ~/miniforge3
          rm -rf ~/miniforge3/miniforge.sh
          ~/miniforge3/bin/conda init bash
          export CONDA=$(realpath ~/miniforge3/bin)
          echo "##vso[task.prependpath]$CONDA"
        displayName: Install conda (Linux)

      - script: conda create --yes --quiet --name ntedit_CI
        displayName: Create Anaconda environment

      - script: |
          source ~/miniforge3/etc/profile.d/conda.sh
          conda activate ntedit_CI
          mamba install --yes -c conda-forge -c bioconda python=3.12 compilers=1.7.0 llvm clang meson ninja btllib make clang-tools perl zlib ntstat ntcard boost snakemake cmake
        displayName: Install dependencies

      - script: |
          source ~/miniforge3/etc/profile.d/conda.sh
          conda activate ntedit_CI
          meson build --prefix=$(pwd)/test_build
          cd build
          ninja install
        displayName: Compile ntEdit

      - script: |
          source ~/miniforge3/etc/profile.d/conda.sh
          conda activate ntedit_CI
          make clang-format
        displayName: Clang-format

      - script: |
          source ~/miniforge3/etc/profile.d/conda.sh
          conda activate ntedit_CI
          export PATH=$(pwd)/test_build/bin:$PATH
          make check
        displayName: Check output files

  - job:
    displayName: mac
    pool:
      vmImage: macOS-latest
    steps:
      - script: |
          mkdir -p ~/miniforge3
          curl -L https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-x86_64.sh -o ~/miniforge3/miniforge.sh
          bash ~/miniforge3/miniforge.sh -b -u -p ~/miniforge3
          rm -rf ~/miniforge3/miniforge.sh
          ~/miniforge3/bin/conda init bash
          ~/miniforge3/bin/conda init zsh
          export CONDA=$(realpath ~/miniforge3/bin)
          echo "##vso[task.prependpath]$CONDA"
        displayName: Install conda (macOS)

      - script: conda create --yes --quiet --name ntedit_CI
        displayName: Create Anaconda environment

      - script: |
          source ~/miniforge3/etc/profile.d/conda.sh
          conda activate ntedit_CI
          mamba install --yes -c conda-forge -c bioconda python compilers=1.7.0 llvm-openmp make btllib perl zlib clang-tools meson ninja ntstat ntcard boost snakemake cmake
        displayName: Install dependencies

      - script: |
          source ~/miniforge3/etc/profile.d/conda.sh
          conda activate ntedit_CI
          meson build --prefix=$(pwd)/test_build
          cd build
          ninja install
        displayName: Compile ntEdit

      - script: |
          source ~/miniforge3/etc/profile.d/conda.sh
          conda activate ntedit_CI
          export PATH=$(pwd)/test_build/bin:$PATH
          make check
        displayName: Check output files
