#https://aka.ms/yaml

jobs:
- job:
  displayName: linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      curl https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-11 main"
      sudo apt-get update -qq
      sudo apt-get install -qq gcc g++ libopenmpi-dev libgtest-dev libomp-dev
      sudo apt-get install -y --no-install-recommends clang-format clang-tidy
    displayName: Install dependencies
  - script: |
      make ntedit
    displayName: Compile ntedit
  - script : |
      make clang-format
    displayName: Clang-format
  - script: |
      make clang-tidy
    displayName: Clang-tidy
  - script : |
      make check
    displayName: Check output files

- job:
  displayName: mac
  pool:
    vmImage: macOS-latest
  steps:
  - script: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  - script: conda create --yes --quiet --name ntedit_ci
    displayName: Create Anaconda environment
  - script: |
      source activate ntedit_ci
      conda install --yes --quiet --name ntedit_ci -c conda-forge -c bioconda llvm-openmp automake autoconf perl zlib
    displayName: Install Anaconda packages
  - script: |
      source activate ntedit_ci
      make ntedit
    displayName: Compile ntedit
  - script: |
      source activate ntedit_ci
      make check
    displayName: Check output files