#https://aka.ms/yaml

jobs:
  - job:
    displayName: linux
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - script: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH
      - script: conda create --yes --quiet --name ntedit_CI
        displayName: Create Anaconda environment
      - script: |
          source activate ntedit_CI
          conda install --yes -c conda-forge mamba python=3.9
          mamba install --yes -c conda-forge -c bioconda libcxx llvm clang compilers=1.7.0 meson ninja btllib make clang-tools perl zlib nthits ntcard boost snakemake cmake
        displayName: Install dependencies
      - script: |
          source activate ntedit_CI
          meson build --prefix=$(pwd)/test_build
          cd build
          ninja install
        displayName: Compile ntedit
      - script: |
          make clang-format
        displayName: Clang-format
      - script: |
          source activate ntedit_CI
          export PATH=$(pwd)/test_build/bin:$PATH
          make check
        displayName: Check output files

  - job:
    displayName: mac
    pool:
      vmImage: macOS-latest
    steps:
      - script: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH
      - script: conda create --yes --quiet --name ntedit_ci
        displayName: Create Anaconda environment
      - script: |
          conda install --yes -c conda-forge mamba python=3.9
          mamba install --yes -c conda-forge -c bioconda llvm-openmp compilers=1.7.0 meson ninja btllib make clang-tools perl zlib nthits ntcard boost snakemake cmake
        displayName: Install dependencies
      - script: |
          source activate ntedit_CI
          meson build --prefix=$(pwd)/test_build
          cd build
          ninja install
        displayName: Compile ntedit
      - script: |
          source activate ntedit_ci
          export PATH=$(pwd)/test_build/bin:$PATH
          make check
        displayName: Check output files
