#https://aka.ms/yaml

jobs:
  - job:
    displayName: linux
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - script: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH
      - script: conda create --yes --quiet --name ntedit_CI
        displayName: Create Anaconda environment
      - script: |
          source activate ntedit_CI
          conda install --yes -c conda-forge mamba python=3.9
          mamba install --yes -c conda-forge -c bioconda compilers meson ninja btllib make clang-tools perl zlib
        displayName: Install dependencies
      - script: |
          source activate ntedit_CI
          git clone https://github.com/bcgsc/ntHash.git
          cd ntHash
          meson build --prefix=$(pwd)/test_install
          cd build
          ninja install
        displayName: Install nthash
      - script: |
          source activate ntedit_CI
          export CPPFLAGS="-isystem $(pwd)/ntHash/test_install/include $CPPFLAGS"
          export LDFLAGS="-L$(pwd)/ntHash/test_install/lib -lnthash $LDFLAGS"
          meson build --prefix=$(pwd)/test_build
          cd build
          ninja install
        displayName: Compile ntedit
      - script: |
          make clang-format
        displayName: Clang-format
      - script: |
          make clang-tidy
        displayName: Clang-tidy
      - script: |
          make check
        displayName: Check output files

  - job:
    displayName: mac
    pool:
      vmImage: macOS-latest
    steps:
      - script: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH
      - script: conda create --yes --quiet --name ntedit_ci
        displayName: Create Anaconda environment
      - script: |
          source activate ntedit_ci
          conda install --yes --quiet --name ntedit_ci -c conda-forge -c bioconda compilers llvm-openmp make btllib perl zlib clang-tools meson ninja
        displayName: Install Anaconda packages
      - script: |
          source activate ntedit_CI
          git clone https://github.com/bcgsc/ntHash.git
          cd ntHash
          meson build --prefix=$(pwd)/test_install
          cd build
          ninja install
        displayName: Install nthash
      - script: |
          source activate ntedit_CI
          export CPPFLAGS="-isystem $(pwd)/ntHash/test_install/include $CPPFLAGS"
          export LDFLAGS="-L$(pwd)/ntHash/test_install/lib -lnthash $LDFLAGS"
          meson build --prefix=$(pwd)/test_build
          cd build
          ninja install
        displayName: Compile ntedit
      - script: |
          source activate ntedit_ci
          make check
        displayName: Check output files
